apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: generator-hpa
  namespace: imv-simulacion
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: generator
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
