apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: imv-simulacion
data:
  DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/imv"
  K8S_NAMESPACE: "imv-simulacion"
  GENERATOR_IMAGE: "ghcr.io/TU_USUARIO/generador:latest"
  BACKEND_URL: "http://backend:5001/api/patients"
