apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: imv-simulacion
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      nodeSelector:
        role: app   
      containers:
      - name: frontend
        image: https://hub.docker.com/r/caedockerid/frontend:latest
        ports:
        - containerPort: 5000
        env:
        - name: BACKEND_URL
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: BACKEND_URL


