apiVersion: batch/v1
kind: Job
metadata:
  generateName: k6-tests-
  namespace: imv-simulacion
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      restartPolicy: Never

      initContainers:
      - name: wait-for-scripts
        image: busybox
        command: ['sh', '-c', 'until [ "$(ls -A /scripts 2>/dev/null)" ]; do echo "Esperando scripts..."; sleep 1; done']
        volumeMounts:
        - name: k6-scripts
          mountPath: /scripts

      containers:
      - name: k6
        image: grafana/k6:latest
        env:
        - name: PIPELINE_ID
          value: "${PIPELINE_ID}"
        - name: K6_OUT
          value: "influxdb=http://influxdb:8086/k6"          
        command: ["sh", "/scripts/run-all.sh"]
        volumeMounts:
        - name: k6-scripts
          mountPath: /scripts
      volumes:
      - name: k6-scripts
        configMap:
          name: k6-scripts
