apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: grafana-configmap-reader
  namespace: imv-simulacion
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
